#!/usr/bin/env python
"""
generate_api.py — autogenerate MyST API-reference fragments from sindae docstrings.

Why this exists
---------------
The documentation site is built with Jupyter Book v2 / mystmd (the JavaScript
MyST engine), which does **not** implement Sphinx's ``autodoc`` directives
(``{autoclass}`` / ``{autofunction}`` are "unknown directives" there — see
https://github.com/jupyter-book/mystmd/issues/1259). This script fills that gap:
it introspects the installed ``sindae`` package with griffe and writes plain,
mystmd-safe MyST fragments — signatures, parameter lists, returns — into
``docs/api/_generated/``. The hand-written pages in ``docs/api/`` pull these in
with the ``{include}`` directive, so prose and usage examples stay separate from
the generated reference.

Usage
-----
    python docs/generate_api.py          # regenerate all fragments

Run it whenever the public API or docstrings change, then rebuild the site
(``jupyter book build --html``). Requires ``griffe`` (see docs/requirements.txt).
"""
from __future__ import annotations

import re
import textwrap
from pathlib import Path

import griffe
from griffe import DocstringSectionKind as K
from griffe import Parser

# --------------------------------------------------------------------------- #
# Manifest: which symbols appear on which page, in order.
# Keys are the page stems under docs/api/; values are object paths relative to
# the sindae package. This mirrors what the old autodoc directives documented.
# --------------------------------------------------------------------------- #
MANIFEST: dict[str, list[str]] = {
    "problem": [
        "problem.ProblemDefinition",
    ],
    "data_utils": [
        "data_utils.TrajectoryData",
        "data_utils.InstanceData",
        "data_utils.extract_instance_data",
        "data_utils.generate_data",
    ],
    "nn_utils": [
        "nn_utils.SimpleMLP",
        "nn_utils.flatten_fn",
        "nn_utils.make_unflatten_fn",
    ],
    "pretrain": [
        "algorithms.pretrain.PretrainConfig",
        "algorithms.pretrain.pretrain_mlp",
    ],
    "smoother": [
        "algorithms.smoother.build_smoother_model",
        "algorithms.smoother.solve_smoother",
    ],
    "simultaneous": [
        "algorithms.simultaneous.train.SimultaneousConfig",
        "algorithms.simultaneous.model_builder.build_simultaneous_model",
        "algorithms.simultaneous.model_builder.build_simultaneous_model_gbm",
        "algorithms.simultaneous.model_builder.extract_mlp",
        "algorithms.simultaneous.train.solve_simultaneous",
    ],
    "decomp": [
        "algorithms.decomp.train.DecompConfig",
        "algorithms.decomp.train.train_decomp",
        "algorithms.decomp.model_builder.build_decomp_model",
    ],
    "inference": [
        "algorithms.inference.make_inference_model",
        "algorithms.inference.solve_inference",
    ],
    "solvers": [
        "solvers.make_nlp_solver",
        "solvers.make_linear_solver",
        "solvers.NLPSolver",
        "solvers.NLPResult",
    ],
}

# Public methods worth documenting on a class even though they are "ordinary"
# (non-dunder) members. Dunder methods are only shown when listed here.
ALWAYS_SHOW_DUNDERS = {"__call__"}

HEADER = (
    "<!-- AUTOGENERATED by docs/generate_api.py — do not edit by hand.\n"
    "     Regenerate with:  python docs/generate_api.py  -->\n"
)


# --------------------------------------------------------------------------- #
# Small formatting helpers
# --------------------------------------------------------------------------- #
def _clean(text: str | None) -> str:
    """Collapse whitespace in a short inline string (types, defaults)."""
    if not text:
        return ""
    return re.sub(r"\s+", " ", str(text)).strip()


def _clean_default(default) -> str | None:
    """Render a parameter default, simplifying dataclasses.field(...) calls."""
    if default is None:
        return None
    s = _clean(default)
    # `field(default=X, repr=False)` -> X ; `field(default_factory=list)` -> list()
    m = re.search(r"\bdefault\s*=\s*([^,)]+)", s)
    if s.startswith("field(") and m:
        return m.group(1).strip()
    m = re.search(r"\bdefault_factory\s*=\s*([^,)]+)", s)
    if s.startswith("field(") and m:
        return f"{m.group(1).strip()}()"
    return s


def _prose(text: str | None) -> str:
    """Dedent / trim a docstring text block for use as MyST prose."""
    if not text:
        return ""
    return textwrap.dedent(text).strip()


def _signature_params(obj) -> list[str]:
    """Render an object's parameters as Python source fragments (skipping self)."""
    out: list[str] = []
    star_emitted = False
    for p in obj.parameters:
        if p.name == "self":
            continue
        kind = p.kind.value
        if kind == "variadic positional":
            out.append(f"*{p.name}")
            star_emitted = True
            continue
        if kind == "variadic keyword":
            out.append(f"**{p.name}")
            continue
        if kind == "keyword-only" and not star_emitted:
            out.append("*")
            star_emitted = True
        frag = p.name
        if p.annotation is not None:
            frag += f": {_clean(p.annotation)}"
        default = _clean_default(p.default)
        if default is not None:
            frag += f" = {default}"
        out.append(frag)
    return out


def _signature(obj, is_class: bool) -> str:
    params = ", ".join(_signature_params(obj))
    if is_class:
        return f"class {obj.name}({params})"
    sig = f"{obj.name}({params})"
    ret = getattr(obj, "returns", None) or getattr(obj, "annotation", None)
    if ret is not None:
        sig += f" -> {_clean(ret)}"
    return sig


def _docstring_sections(obj) -> dict:
    """Map section kind -> parsed value for an object's docstring."""
    sections: dict = {}
    if obj.docstring is None:
        return sections
    for sec in obj.docstring.parsed:
        sections.setdefault(sec.kind, sec.value)
    return sections


def _param_descriptions(sections) -> dict[str, str]:
    descs: dict[str, str] = {}
    for item in sections.get(K.parameters, []) or []:
        descs[item.name] = _clean(item.description)
    return descs


def _render_param_list(obj, sections) -> list[str]:
    """Bullet list of parameters, merging signature types with docstring text."""
    descs = _param_descriptions(sections)
    lines: list[str] = []
    for p in obj.parameters:
        if p.name == "self":
            continue
        if p.kind.value in ("variadic positional", "variadic keyword"):
            name = ("*" if p.kind.value == "variadic positional" else "**") + p.name
        else:
            name = p.name
        meta = []
        if p.annotation is not None:
            meta.append(f"`{_clean(p.annotation)}`")
        default = _clean_default(p.default)
        if default is not None:
            meta.append(f"default `{default}`")
        bullet = f"- **`{name}`**"
        if meta:
            bullet += " (" + ", ".join(meta) + ")"
        desc = descs.get(p.name, "")
        if desc:
            bullet += f" — {desc}"
        lines.append(bullet)
    return lines


def _render_returns(obj, sections) -> list[str]:
    lines: list[str] = []
    rets = sections.get(K.returns)
    if rets:
        for item in rets:
            name = getattr(item, "name", None)
            ann = _clean(item.annotation)
            desc = _clean(item.description)
            bullet = "- "
            if name:
                bullet += f"**`{name}`** "
            if ann:
                bullet += f"(`{ann}`)"
            if desc:
                bullet += f" — {desc}"
            lines.append(bullet.rstrip())
    else:
        ret = getattr(obj, "returns", None)
        if ret is not None and _clean(ret) not in ("None", ""):
            lines.append(f"- `{_clean(ret)}`")
    return lines


def _render_raises(sections) -> list[str]:
    lines: list[str] = []
    for item in sections.get(K.raises, []) or []:
        ann = _clean(item.annotation)
        desc = _clean(item.description)
        bullet = f"- `{ann}`" if ann else "-"
        if desc:
            bullet += f" — {desc}"
        lines.append(bullet)
    return lines


def _render_callable(obj, level: int) -> list[str]:
    """Render a function or method at the given heading level."""
    hashes = "#" * level
    label = obj.canonical_path
    sections = _docstring_sections(obj)
    out = [f"({label})=", f"{hashes} `{obj.name}`", ""]
    out += ["```python", _signature(obj, is_class=False), "```", ""]
    prose = _prose(sections.get(K.text))
    if prose:
        out += [prose, ""]
    params = _render_param_list(obj, sections)
    if params:
        out += ["**Parameters**", "", *params, ""]
    returns = _render_returns(obj, sections)
    if returns:
        out += ["**Returns**", "", *returns, ""]
    raises = _render_raises(sections)
    if raises:
        out += ["**Raises**", "", *raises, ""]
    return out


def _is_dataclass(cls) -> bool:
    return "dataclass" in {str(x) for x in (cls.labels or set())}


def _render_class(cls) -> list[str]:
    label = cls.canonical_path
    sections = _docstring_sections(cls)
    out = [f"({label})=", f"### `{cls.name}`", ""]
    out += ["```python", _signature(cls, is_class=True), "```", ""]
    prose = _prose(sections.get(K.text))
    if prose:
        out += [prose, ""]

    if _is_dataclass(cls):
        fields = _render_param_list(cls, sections)
        if fields:
            out += ["**Fields**", "", *fields, ""]
        return out

    # Constructor parameters (from __init__ docstring, surfaced on the class).
    params = _render_param_list(cls, sections)
    if params:
        out += ["**Parameters**", "", *params, ""]

    # Properties (attributes flagged as property, with a docstring).
    props = []
    for name, member in cls.members.items():
        if name.startswith("_"):
            continue
        labels = {str(x) for x in (getattr(member, "labels", set()) or set())}
        if member.kind.value == "attribute" and "property" in labels:
            doc = _prose(member.docstring.value) if member.docstring else ""
            props.append(f"- **`{name}`** — {doc}" if doc else f"- **`{name}`**")
    if props:
        out += ["**Properties**", "", *props, ""]

    # Methods (public functions + selected dunders).
    methods = []
    for name, member in cls.members.items():
        if member.kind.value != "function":
            continue
        if name.startswith("_") and name not in ALWAYS_SHOW_DUNDERS:
            continue
        methods.append(member)
    if methods:
        out += ["**Methods**", ""]
        for m in methods:
            out += _render_callable(m, level=4)
    return out


def render_object(pkg, path: str) -> str:
    obj = pkg[path]
    if obj.kind.value == "class":
        lines = _render_class(obj)
    else:
        lines = _render_callable(obj, level=3)
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    here = Path(__file__).resolve().parent          # docs/
    repo_root = here.parent
    out_dir = here / "api" / "_generated"
    out_dir.mkdir(parents=True, exist_ok=True)

    pkg = griffe.load(
        "sindae",
        docstring_parser=Parser.numpy,
        search_paths=[str(repo_root)],
    )

    for page, paths in MANIFEST.items():
        chunks = [render_object(pkg, p) for p in paths]
        body = HEADER + "\n" + "\n\n".join(chunks)
        (out_dir / f"{page}.md").write_text(body)
        print(f"  wrote api/_generated/{page}.md  ({len(paths)} symbols)")

    print(f"Done. {len(MANIFEST)} fragments written to {out_dir}")


if __name__ == "__main__":
    main()
